### PR TITLE
Fix tests and enable 'reportErrorsOnly' by default

### PR DESCRIPTION
**Pull request by JonasAlaif**
By default Prusti Assistant show forward Rustc warnings to the user

### CODE REVIEW

**Review by fpoli — COMMENTED** [review]
Oh, I forgot about the tests. Could you add `#[allow(...)]` annotations to the tests and add the remaining new diagnostics to the expected output ([example](https://github.com/viperproject/prusti-assistant/blob/master/src/test/data/programs/failing_post.rs.json))?

**Comment by JonasAlaif** [comment]
Yep, lets see if this works

**Comment by JonasAlaif** [comment]
@fpoli 😢

**Comment by fpoli** [comment]
Ouch. For some reason on Mac the output is different, but the error message doesn't show the full expected object and I cannot guess it.

To fix this, I would change the array-of-array-of-diagnostics to a dictionary-of-arrays-of-diagnostics, where the keys of the outer dictionary are `"{buildChannel}_{OS}"` values or `"default"`. This way, the test suite can pick the exact array of expected diagnostics and show a nice diff.

**Pull request merged**
