### PR TITLE
Prusti Server Integration & UX/UI Enhancements

### PR DESCRIPTION
**Pull request by juliand665**
Unit tests are currently doomed to fail because prusti-server doesn't seem to be part of the Prusti Distributable package this downloads.

### CODE REVIEW

**Comment by vakaras** [comment]
CI is failing because it tries to access the repository via SSH. I guess this is not how it should be, right?

**Comment by juliand665** [comment]
Oh huh, looks like there was still an SSH url in the package-lock.json. I'll regenerate that and push again.

**Comment by vakaras** [comment]
Could you please poke once I should look into it?

**Comment by juliand665** [comment]
All right, I updated the node version travis was using and now it produces the same error as the github actions CI on all 3 platforms, if that's any help.

**Comment by fpoli** [comment]
What's the status here? Should it be enough to wait until `prusti-server` is distributed in the zip?

**Comment by vakaras** [comment]
> What's the status here? Should it be enough to wait until `prusti-server` is distributed in the zip?

Yes, it should be enough.

**Comment by juliand665** [comment]
Yeah, if it still fails after that, I'll definitely take a look at it—right now, it's infeasible to anticipate what issues might pop up with the CI, but locally (using a local reference to a working prusti export), all tests pass just fine.

**Comment by fpoli** [comment]
It seems that I cannot push to this PR. I'll close and include all commits in PR #4.

**Comment by juliand665** [comment]
> It seems that I cannot push to this PR.
Ah yes, looks like I forgot to check this box. All good.
image

**Pull request closed without merging**
